name: Deploy Development

on:
  push:
    branches: [dev]

jobs:
 deploy:
  runs-on: ubuntu-latest
  permissions:
    contents: write
  steps:
  - uses: actions/checkout@v6
  - uses: actions/setup-node@v6
    with:
      node-version: 26
  - run: npm ci
  - run: npm run build -- --mode development
  - uses: peaceiris/actions-gh-pages@v4
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./dist
      destination_dir: dev # deploys to /dev/ subfolder